from __future__ import annotations

from pathlib import Path

from .config import LABEL_DEFINITIONS
from .labels import label_summary, public_labels
from .pairings import build_pairings
from .scoring import score_row
from .utils import confirmed, eastern_now, number, read_csv, safe_round, write_json


ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = ROOT / "outputs"


def build_from_rankings(input_csv: Path, output_json: Path) -> dict:
    raw_rows = read_csv(input_csv)
    rows = []
    for row in raw_rows:
        scored = score_row(row)
        scored["labels"] = public_labels(scored)
        scored["label_summary"] = label_summary(scored)
        rows.append(scored)

    rows = sorted(rows, key=lambda row: number(row.get("ghost_score")), reverse=True)
    for idx, row in enumerate(rows, 1):
        row["ghost_rank"] = idx

    confirmed_rows = [row for row in rows if confirmed(row.get("confirmed_lineup"))]
    projected_rows = [row for row in rows if not confirmed(row.get("confirmed_lineup"))]
    pair_source = confirmed_rows if len(confirmed_rows) >= 8 else rows

    now = eastern_now()
    payload = {
        "brand": "Ghost Analytics",
        "product": "BarrelIQ",
        "date": now.strftime("%A, %B %-d, %Y"),
        "generated_at": now.strftime("%I:%M %p %Z"),
        "generated_iso": now.isoformat(),
        "timezone": "Eastern Time",
        "status": {
            "mode": "live_refresh",
            "freshness": "scheduled_live_payload",
            "source_health": "fresh automated slate, rankings, labels, pairings, and audit stub generated by GhostIQ workflow",
            "confirmed_count": len(confirmed_rows),
            "projected_count": len(projected_rows),
            "total_players": len(rows),
        },
        "top_targets": [target_payload(row) for row in rows[:30]],
        "confirmed_targets": [target_payload(row) for row in confirmed_rows[:30]],
        "projected_targets": [target_payload(row) for row in projected_rows[:30]],
        "pairings": {
            "2": build_pairings(pair_source, 2),
            "3": build_pairings(pair_source, 3),
            "4": build_pairings(pair_source, 4),
        },
        "weather_edges": weather_edges(rows),
        "label_definitions": LABEL_DEFINITIONS,
        "audit_summary": {
            "status": "framework_ready",
            "message": "Nightly audit engine scaffold is active; final result comparison will be wired after collectors.",
        },
        "model_profile": {
            "public_scoring": "Ghost Grade + Edge Index + Confidence + Volatility",
            "data_years": "2026 primary, 2025 support",
            "public_label_policy": "Only active model signals are shown on the dashboard.",
        },
    }
    write_json(output_json, payload)
    return payload


def target_payload(row: dict) -> dict:
    return {
        "rank": row.get("ghost_rank"),
        "player": row.get("player"),
        "team": row.get("team"),
        "opponent": row.get("opponent"),
        "matchup": f"{row.get('team')} vs {row.get('opponent')}",
        "batting_order": row.get("batting_order"),
        "pitcher": row.get("pitcher"),
        "pitcher_hand": row.get("pitcher_hand"),
        "ballpark": row.get("ballpark"),
        "game_start_time": row.get("game_start_time"),
        "confirmed": confirmed(row.get("confirmed_lineup")),
        "edge_index": row.get("edge_index"),
        "ghost_grade": row.get("ghost_grade"),
        "confidence": row.get("confidence"),
        "volatility": row.get("volatility"),
        "labels": row.get("labels", []),
        "label_summary": row.get("label_summary"),
        "components": row.get("components"),
        "legacy_hr_score": safe_round(row.get("hr_score")),
    }


def weather_edges(rows: list[dict]) -> list[dict]:
    parks: dict[str, list[dict]] = {}
    for row in rows:
        park = str(row.get("ballpark") or "Unknown")
        parks.setdefault(park, []).append(row)

    edges = []
    for park, park_rows in parks.items():
        best = max(park_rows, key=lambda row: number(row.get("edge_index")))
        env = sum(number(row.get("environment_score")) for row in park_rows) / len(park_rows)
        if env < 50 and "Weather Edge" not in best.get("labels", []):
            continue
        edges.append(
            {
                "ballpark": park,
                "environment_score": round(env, 1),
                "top_player": best.get("player"),
                "top_edge": best.get("edge_index"),
                "teams": sorted({str(row.get("team")) for row in park_rows}),
            }
        )
    return sorted(edges, key=lambda item: item["environment_score"], reverse=True)[:10]
